//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRA.Identity.Client.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRA.Identity.Client.Resources.Languages.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Dashboard_Appilcations_Action {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant response.
        /// </summary>
        internal static string Dashboard_Appilcations_Applicant_response {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Applicant response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant username.
        /// </summary>
        internal static string Dashboard_Appilcations_Applicant_username {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Applicant username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string Dashboard_Appilcations_Applications {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied at.
        /// </summary>
        internal static string Dashboard_Appilcations_Applied_at {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Applied at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoverLetter.
        /// </summary>
        internal static string Dashboard_Appilcations_CoverLetter {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:CoverLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string Dashboard_Appilcations_More {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Dashboard_Appilcations_Name {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug.
        /// </summary>
        internal static string Dashboard_Appilcations_Slug {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status name.
        /// </summary>
        internal static string Dashboard_Appilcations_Status_name {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Status name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusName.
        /// </summary>
        internal static string Dashboard_Appilcations_StatusName {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:StatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacancy title.
        /// </summary>
        internal static string Dashboard_Appilcations_Vacancy_title {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:Vacancy title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VacancyResponses.
        /// </summary>
        internal static string Dashboard_Appilcations_VacancyResponses {
            get {
                return ResourceManager.GetString("Dashboard:Appilcations:VacancyResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Myself.
        /// </summary>
        internal static string FltValidator_AboutMyself {
            get {
                return ResourceManager.GetString("FltValidator:AboutMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string FltValidator_Address {
            get {
                return ResourceManager.GetString("FltValidator:Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string FltValidator_Code {
            get {
                return ResourceManager.GetString("FltValidator:Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string FltValidator_Comment {
            get {
                return ResourceManager.GetString("FltValidator:Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string FltValidator_CompanyName {
            get {
                return ResourceManager.GetString("FltValidator:CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string FltValidator_Date {
            get {
                return ResourceManager.GetString("FltValidator:Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        internal static string FltValidator_DateOfBirth {
            get {
                return ResourceManager.GetString("FltValidator:DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string FltValidator_Description {
            get {
                return ResourceManager.GetString("FltValidator:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educations.
        /// </summary>
        internal static string FltValidator_Educations {
            get {
                return ResourceManager.GetString("FltValidator:Educations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string FltValidator_EndDate {
            get {
                return ResourceManager.GetString("FltValidator:EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiences.
        /// </summary>
        internal static string FltValidator_Experiences {
            get {
                return ResourceManager.GetString("FltValidator:Experiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FltValidator_FirstName {
            get {
                return ResourceManager.GetString("FltValidator:FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string FltValidator_Gender {
            get {
                return ResourceManager.GetString("FltValidator:Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string FltValidator_Id {
            get {
                return ResourceManager.GetString("FltValidator:Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is CurrentJob.
        /// </summary>
        internal static string FltValidator_IsCurrentJob {
            get {
                return ResourceManager.GetString("FltValidator:IsCurrentJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        internal static string FltValidator_JobTitle {
            get {
                return ResourceManager.GetString("FltValidator:JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string FltValidator_LastName {
            get {
                return ResourceManager.GetString("FltValidator:LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FltValidator_Name {
            get {
                return ResourceManager.GetString("FltValidator:Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string FltValidator_PhoneNumber {
            get {
                return ResourceManager.GetString("FltValidator:PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender User Name.
        /// </summary>
        internal static string FltValidator_SenderUserName {
            get {
                return ResourceManager.GetString("FltValidator:SenderUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent At.
        /// </summary>
        internal static string FltValidator_SentAt {
            get {
                return ResourceManager.GetString("FltValidator:SentAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug.
        /// </summary>
        internal static string FltValidator_Slug {
            get {
                return ResourceManager.GetString("FltValidator:Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality.
        /// </summary>
        internal static string FltValidator_Speciality {
            get {
                return ResourceManager.GetString("FltValidator:Speciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string FltValidator_StartDate {
            get {
                return ResourceManager.GetString("FltValidator:StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string FltValidator_Status {
            get {
                return ResourceManager.GetString("FltValidator:Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string FltValidator_Subject {
            get {
                return ResourceManager.GetString("FltValidator:Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string FltValidator_Text {
            get {
                return ResourceManager.GetString("FltValidator:Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        internal static string FltValidator_University {
            get {
                return ResourceManager.GetString("FltValidator:University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until Now.
        /// </summary>
        internal static string FltValidator_UntilNow {
            get {
                return ResourceManager.GetString("FltValidator:UntilNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string FltValidator_User {
            get {
                return ResourceManager.GetString("FltValidator:User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        internal static string FltValidator_UserId {
            get {
                return ResourceManager.GetString("FltValidator:UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string FltValidator_UserName {
            get {
                return ResourceManager.GetString("FltValidator:UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Skills.
        /// </summary>
        internal static string FltValidator_UserSkills {
            get {
                return ResourceManager.GetString("FltValidator:UserSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academy.
        /// </summary>
        internal static string Header_Academy {
            get {
                return ResourceManager.GetString("Header:Academy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Header_Home {
            get {
                return ResourceManager.GetString("Header:Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string Header_Jobs {
            get {
                return ResourceManager.GetString("Header:Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email.
        /// </summary>
        internal static string Header_SendEmail {
            get {
                return ResourceManager.GetString("Header:SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        internal static string Header_SendMessage {
            get {
                return ResourceManager.GetString("Header:SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string Header_Team {
            get {
                return ResourceManager.GetString("Header:Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Home_Address {
            get {
                return ResourceManager.GetString("Home:Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Message_Comment {
            get {
                return ResourceManager.GetString("Message:Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message_Message {
            get {
                return ResourceManager.GetString("Message:Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Message_Send {
            get {
                return ResourceManager.GetString("Message:Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Myself.
        /// </summary>
        internal static string Profile_AboutMyself {
            get {
                return ResourceManager.GetString("Profile:AboutMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Education.
        /// </summary>
        internal static string Profile_AddNewEducation {
            get {
                return ResourceManager.GetString("Profile:AddNewEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Experience.
        /// </summary>
        internal static string Profile_AddNewExperience {
            get {
                return ResourceManager.GetString("Profile:AddNewExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Skill.
        /// </summary>
        internal static string Profile_AddSkill {
            get {
                return ResourceManager.GetString("Profile:AddSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Skills successfully..
        /// </summary>
        internal static string Profile_AddSkillssuccessfully {
            get {
                return ResourceManager.GetString("Profile:AddSkillssuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string Profile_Anerroroccurred {
            get {
                return ResourceManager.GetString("Profile:Anerroroccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Profile_Cancel {
            get {
                return ResourceManager.GetString("Profile:Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is incorrect or expired.
        /// </summary>
        internal static string Profile_Codeisincorrector {
            get {
                return ResourceManager.GetString("Profile:Codeisincorrector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code sent.
        /// </summary>
        internal static string Profile_Codesent {
            get {
                return ResourceManager.GetString("Profile:Codesent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string Profile_CompanyName {
            get {
                return ResourceManager.GetString("Profile:CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Profile_Confirm {
            get {
                return ResourceManager.GetString("Profile:Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation code.
        /// </summary>
        internal static string Profile_Confirmationcode {
            get {
                return ResourceManager.GetString("Profile:Confirmationcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string Profile_Confirmed {
            get {
                return ResourceManager.GetString("Profile:Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Job.
        /// </summary>
        internal static string Profile_CurrentJob {
            get {
                return ResourceManager.GetString("Profile:CurrentJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        internal static string Profile_DateOfBirth {
            get {
                return ResourceManager.GetString("Profile:DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Profile_Delete {
            get {
                return ResourceManager.GetString("Profile:Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Profile_Description {
            get {
                return ResourceManager.GetString("Profile:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete these records? This process cannot be undone..
        /// </summary>
        internal static string Profile_Doyoureally {
            get {
                return ResourceManager.GetString("Profile:Doyoureally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education details added successfully.
        /// </summary>
        internal static string Profile_Educationdetailsadded {
            get {
                return ResourceManager.GetString("Profile:Educationdetailsadded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educations.
        /// </summary>
        internal static string Profile_Educations {
            get {
                return ResourceManager.GetString("Profile:Educations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not available.
        /// </summary>
        internal static string Profile_Emailisnotavailable {
            get {
                return ResourceManager.GetString("Profile:Emailisnotavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not Confirmed!.
        /// </summary>
        internal static string Profile_EmailisnotConfirmed {
            get {
                return ResourceManager.GetString("Profile:EmailisnotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string Profile_EndDate {
            get {
                return ResourceManager.GetString("Profile:EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        internal static string Profile_Experience {
            get {
                return ResourceManager.GetString("Profile:Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience details added successfully...
        /// </summary>
        internal static string Profile_Experiencedetailsadded {
            get {
                return ResourceManager.GetString("Profile:Experiencedetailsadded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiences.
        /// </summary>
        internal static string Profile_Experiences {
            get {
                return ResourceManager.GetString("Profile:Experiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string Profile_FirstName {
            get {
                return ResourceManager.GetString("Profile:FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you would like to nominate yourself, send us your СV..
        /// </summary>
        internal static string Profile_Ifyouwouldliketonominateyourself_sendusyourСV_ {
            get {
                return ResourceManager.GetString("Profile:Ifyouwouldliketonominateyourself,sendusyourСV.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  If you would like to nominate yourself, sign in and send us your СV..
        /// </summary>
        internal static string Profile_Ifyouwouldliketonominateyourself_signinandsendusyourСV_ {
            get {
                return ResourceManager.GetString("Profile:Ifyouwouldliketonominateyourself,signinandsendusyourСV.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Current Job.
        /// </summary>
        internal static string Profile_IsCurrentJob {
            get {
                return ResourceManager.GetString("Profile:IsCurrentJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        internal static string Profile_JobTitle {
            get {
                return ResourceManager.GetString("Profile:JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Profile_LastName {
            get {
                return ResourceManager.GetString("Profile:LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string Profile_MyProfile {
            get {
                return ResourceManager.GetString("Profile:MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Education.
        /// </summary>
        internal static string Profile_NewEducation {
            get {
                return ResourceManager.GetString("Profile:NewEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Experience.
        /// </summary>
        internal static string Profile_NewExperience {
            get {
                return ResourceManager.GetString("Profile:NewExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string Profile_OldPassword {
            get {
                return ResourceManager.GetString("Profile:OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string Profile_PersonalInformation {
            get {
                return ResourceManager.GetString("Profile:PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number is not available.
        /// </summary>
        internal static string Profile_PhoneNumberisnotavailable {
            get {
                return ResourceManager.GetString("Profile:PhoneNumberisnotavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number is not Confirmed!.
        /// </summary>
        internal static string Profile_PhoneNumberisnotConfirmed {
            get {
                return ResourceManager.GetString("Profile:PhoneNumberisnotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email, we sent verification link.
        /// </summary>
        internal static string Profile_Pleasecheckyouremail {
            get {
                return ResourceManager.GetString("Profile:Pleasecheckyouremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        internal static string Profile_Present {
            get {
                return ResourceManager.GetString("Profile:Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfully..
        /// </summary>
        internal static string Profile_Profileupdatedsuccessfully {
            get {
                return ResourceManager.GetString("Profile:Profileupdatedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password successfully.
        /// </summary>
        internal static string Profile_Resetpasswordsuccessfully {
            get {
                return ResourceManager.GetString("Profile:Resetpasswordsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Profile_Save {
            get {
                return ResourceManager.GetString("Profile:Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string Profile_Savechanges {
            get {
                return ResourceManager.GetString("Profile:Savechanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string Profile_SelectLanguage {
            get {
                return ResourceManager.GetString("Profile:SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification email.
        /// </summary>
        internal static string Profile_Sendverificationemail {
            get {
                return ResourceManager.GetString("Profile:Sendverificationemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is not responding.
        /// </summary>
        internal static string Profile_Serverisnotresponding {
            get {
                return ResourceManager.GetString("Profile:Serverisnotresponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server not responding, try again latter.
        /// </summary>
        internal static string Profile_Servernotrespondingtry {
            get {
                return ResourceManager.GetString("Profile:Servernotrespondingtry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string Profile_Skills {
            get {
                return ResourceManager.GetString("Profile:Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty.
        /// </summary>
        internal static string Profile_Specialty {
            get {
                return ResourceManager.GetString("Profile:Specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string Profile_StartDate {
            get {
                return ResourceManager.GetString("Profile:StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Switch to Dark Theme.
        /// </summary>
        internal static string Profile_SwitchtoDarkTheme {
            get {
                return ResourceManager.GetString("Profile:SwitchtoDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Switch to Light Theme.
        /// </summary>
        internal static string Profile_SwitchtoLightTheme {
            get {
                return ResourceManager.GetString("Profile:SwitchtoLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Switch to system.
        /// </summary>
        internal static string Profile_Switchtosystem {
            get {
                return ResourceManager.GetString("Profile:Switchtosystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The status of your CV for your candidacy is.
        /// </summary>
        internal static string Profile_ThestatusofyourCVforyourcandidacyis {
            get {
                return ResourceManager.GetString("Profile:ThestatusofyourCVforyourcandidacyis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phone number is not correct !.
        /// </summary>
        internal static string Profile_Thisphonenumberisnotcorrect {
            get {
                return ResourceManager.GetString("Profile:Thisphonenumberisnotcorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change your password, enter your current password, and then create a new, strong password..
        /// </summary>
        internal static string Profile_Tochangeyourpassword_enteryouroldpassword_andthencreateanew_strongpassword_ {
            get {
                return ResourceManager.GetString("Profile:Tochangeyourpassword,enteryouroldpassword,andthencreateanew,strongpasswor" +
                        "d.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        internal static string Profile_TryAgain {
            get {
                return ResourceManager.GetString("Profile:TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        internal static string Profile_University {
            get {
                return ResourceManager.GetString("Profile:University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until Now.
        /// </summary>
        internal static string Profile_UntilNow {
            get {
                return ResourceManager.GetString("Profile:UntilNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Profile_Update {
            get {
                return ResourceManager.GetString("Profile:Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Education successfully..
        /// </summary>
        internal static string Profile_UpdateEducationsuccessfully {
            get {
                return ResourceManager.GetString("Profile:UpdateEducationsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload CV.
        /// </summary>
        internal static string Profile_UploadCV {
            get {
                return ResourceManager.GetString("Profile:UploadCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Upload New CV.
        /// </summary>
        internal static string Profile_UploadNewCV {
            get {
                return ResourceManager.GetString("Profile:UploadNewCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is not available.
        /// </summary>
        internal static string Profile_UserNameisnotavailable {
            get {
                return ResourceManager.GetString("Profile:UserNameisnotavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ResetPassword_Changepassword {
            get {
                return ResourceManager.GetString("ResetPassword:Changepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password successfully.
        /// </summary>
        internal static string ResetPassword_Changepasswordsuccessfully {
            get {
                return ResourceManager.GetString("ResetPassword:Changepasswordsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string ResetPassword_NewPassword {
            get {
                return ResourceManager.GetString("ResetPassword:NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string ResetPassword_PhoneNumber {
            get {
                return ResourceManager.GetString("ResetPassword:PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend code.
        /// </summary>
        internal static string ResetPassword_Resendcode {
            get {
                return ResourceManager.GetString("ResetPassword:Resendcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send confirmation code.
        /// </summary>
        internal static string ResetPassword_Sendconfirmationcode {
            get {
                return ResourceManager.GetString("ResetPassword:Sendconfirmationcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? Go to.
        /// </summary>
        internal static string SignIn_LabelDontAccount {
            get {
                return ResourceManager.GetString("SignIn:LabelDontAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string SignIn_LabelForgot {
            get {
                return ResourceManager.GetString("SignIn:LabelForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string SignIn_LinkReset {
            get {
                return ResourceManager.GetString("SignIn:LinkReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignIn_LinkSignUp {
            get {
                return ResourceManager.GetString("SignIn:LinkSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SignIn_Password {
            get {
                return ResourceManager.GetString("SignIn:Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn_SignIn {
            get {
                return ResourceManager.GetString("SignIn:SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string SignIn_UserName {
            get {
                return ResourceManager.GetString("SignIn:UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password.
        /// </summary>
        internal static string SignIn_Wrong_Password {
            get {
                return ResourceManager.GetString("SignIn:Wrong Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string SignUp_Apply {
            get {
                return ResourceManager.GetString("SignUp:Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string SignUp_ButtonNext {
            get {
                return ResourceManager.GetString("SignUp:ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string SignUp_Code {
            get {
                return ResourceManager.GetString("SignUp:Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string SignUp_ConfirmPassword {
            get {
                return ResourceManager.GetString("SignUp:ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string SignUp_ConfirmPassword_HelperText {
            get {
                return ResourceManager.GetString("SignUp:ConfirmPassword_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string SignUp_Email {
            get {
                return ResourceManager.GetString("SignUp:Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue With.
        /// </summary>
        internal static string SignUp_ExternalLoginCard {
            get {
                return ResourceManager.GetString("SignUp:ExternalLoginCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string SignUp_FirstName {
            get {
                return ResourceManager.GetString("SignUp:FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your first name.
        /// </summary>
        internal static string SignUp_FirstName_HelperText {
            get {
                return ResourceManager.GetString("SignUp:FirstName_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have an account? Go to.
        /// </summary>
        internal static string SignUp_LabelHaveAccount {
            get {
                return ResourceManager.GetString("SignUp:LabelHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp_LabelSignUp {
            get {
                return ResourceManager.GetString("SignUp:LabelSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string SignUp_LastName {
            get {
                return ResourceManager.GetString("SignUp:LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your last name.
        /// </summary>
        internal static string SignUp_LastName_HelperText {
            get {
                return ResourceManager.GetString("SignUp:LastName_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Sign In.
        /// </summary>
        internal static string SignUp_LinkSignIn {
            get {
                return ResourceManager.GetString("SignUp:LinkSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent a confirmation code to this number: $phone$. Please enter the code below to confirm your identity..
        /// </summary>
        internal static string signUp_messageText {
            get {
                return ResourceManager.GetString("signUp:messageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SignUp_Password {
            get {
                return ResourceManager.GetString("SignUp:Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SignUp_Password_HelperText {
            get {
                return ResourceManager.GetString("SignUp:Password_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string SignUp_Phone {
            get {
                return ResourceManager.GetString("SignUp:Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number.
        /// </summary>
        internal static string SignUp_Phone_HelperText {
            get {
                return ResourceManager.GetString("SignUp:Phone_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend code.
        /// </summary>
        internal static string SignUp_ResendCode {
            get {
                return ResourceManager.GetString("SignUp:ResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds left to resend the code..
        /// </summary>
        internal static string SignUp_Secconds {
            get {
                return ResourceManager.GetString("SignUp:Secconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string SignUp_UserName {
            get {
                return ResourceManager.GetString("SignUp:UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string UserButton_Applications {
            get {
                return ResourceManager.GetString("UserButton:Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string UserButton_Logout {
            get {
                return ResourceManager.GetString("UserButton:Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string UserButton_Profile {
            get {
                return ResourceManager.GetString("UserButton:Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string UserButton_Sign_In {
            get {
                return ResourceManager.GetString("UserButton:Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string UserButton_Sign_Up {
            get {
                return ResourceManager.GetString("UserButton:Sign Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string UserManager_FullName {
            get {
                return ResourceManager.GetString("UserManager:FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string UserManager_Loading {
            get {
                return ResourceManager.GetString("UserManager:Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching records found.
        /// </summary>
        internal static string UserManager_Nomatchingrecords {
            get {
                return ResourceManager.GetString("UserManager:Nomatchingrecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string UserManager_Roles {
            get {
                return ResourceManager.GetString("UserManager:Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by username or full name.
        /// </summary>
        internal static string UserManager_Searchname {
            get {
                return ResourceManager.GetString("UserManager:Searchname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string UserManager_Users {
            get {
                return ResourceManager.GetString("UserManager:Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string UserRoles_Gender {
            get {
                return ResourceManager.GetString("UserRoles:Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string UserRoles_History {
            get {
                return ResourceManager.GetString("UserRoles:History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Data.
        /// </summary>
        internal static string UserRoles_PersonalData {
            get {
                return ResourceManager.GetString("UserRoles:PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnConfirmed.
        /// </summary>
        internal static string UserRoles_UnConfirmed {
            get {
                return ResourceManager.GetString("UserRoles:UnConfirmed", resourceCulture);
            }
        }
    }
}
