//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRA.Identity.Client.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tajik {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tajik() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRA.Identity.Client.Resources.Languages.Tajik", typeof(Tajik).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Академия.
        /// </summary>
        internal static string Header_Academy {
            get {
                return ResourceManager.GetString("Header:Academy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Асосӣ.
        /// </summary>
        internal static string Header_Home {
            get {
                return ResourceManager.GetString("Header:Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ҷойҳои корӣ.
        /// </summary>
        internal static string Header_Jobs {
            get {
                return ResourceManager.GetString("Header:Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тим.
        /// </summary>
        internal static string Header_Team {
            get {
                return ResourceManager.GetString("Header:Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Суроға.
        /// </summary>
        internal static string Home_Address {
            get {
                return ResourceManager.GetString("Home:Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дар бораи худ.
        /// </summary>
        internal static string Profile_AboutMyself {
            get {
                return ResourceManager.GetString("Profile:AboutMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таълими нав илова кунед.
        /// </summary>
        internal static string Profile_AddNewEducation {
            get {
                return ResourceManager.GetString("Profile:AddNewEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таҷрибаи нав илова кунед.
        /// </summary>
        internal static string Profile_AddNewExperience {
            get {
                return ResourceManager.GetString("Profile:AddNewExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маҳорат илова кунед.
        /// </summary>
        internal static string Profile_AddSkill {
            get {
                return ResourceManager.GetString("Profile:AddSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маҳоратҳо бомувафақият инсон карда шуданд.
        /// </summary>
        internal static string Profile_AddSkillssuccessfully {
            get {
                return ResourceManager.GetString("Profile:AddSkillssuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рӯй хато рӯй бурд.
        /// </summary>
        internal static string Profile_Anerroroccurred {
            get {
                return ResourceManager.GetString("Profile:Anerroroccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бекор кунед.
        /// </summary>
        internal static string Profile_Cancel {
            get {
                return ResourceManager.GetString("Profile:Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код нодуруст ё устурашидааст.
        /// </summary>
        internal static string Profile_Codeisincorrector {
            get {
                return ResourceManager.GetString("Profile:Codeisincorrector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код фиристода шуд.
        /// </summary>
        internal static string Profile_Codesent {
            get {
                return ResourceManager.GetString("Profile:Codesent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номи ширкат.
        /// </summary>
        internal static string Profile_CompanyName {
            get {
                return ResourceManager.GetString("Profile:CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тасдиқ кунед.
        /// </summary>
        internal static string Profile_Confirm {
            get {
                return ResourceManager.GetString("Profile:Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коди тасдиқ.
        /// </summary>
        internal static string Profile_Confirmationcode {
            get {
                return ResourceManager.GetString("Profile:Confirmationcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тасдиқ шуд.
        /// </summary>
        internal static string Profile_Confirmed {
            get {
                return ResourceManager.GetString("Profile:Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кори ҷорӣ.
        /// </summary>
        internal static string Profile_CurrentJob {
            get {
                return ResourceManager.GetString("Profile:CurrentJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Санаи таваллуд.
        /// </summary>
        internal static string Profile_DateOfBirth {
            get {
                return ResourceManager.GetString("Profile:DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неcхтан.
        /// </summary>
        internal static string Profile_Delete {
            get {
                return ResourceManager.GetString("Profile:Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тавсиф.
        /// </summary>
        internal static string Profile_Description {
            get {
                return ResourceManager.GetString("Profile:Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оё шумо дар хакикат мехоҳед ин рамзҳоро нест кунед? Ин амал ба ҳолати гузашта наметавонад..
        /// </summary>
        internal static string Profile_Doyoureally {
            get {
                return ResourceManager.GetString("Profile:Doyoureally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маълумоти таълимӣ бомувафақият инсон карда шуд.
        /// </summary>
        internal static string Profile_Educationdetailsadded {
            get {
                return ResourceManager.GetString("Profile:Educationdetailsadded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таълим.
        /// </summary>
        internal static string Profile_Educations {
            get {
                return ResourceManager.GetString("Profile:Educations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email дастгирӣ нашудааст.
        /// </summary>
        internal static string Profile_Emailisnotavailable {
            get {
                return ResourceManager.GetString("Profile:Emailisnotavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейл тасдиқ нашудааст!.
        /// </summary>
        internal static string Profile_EmailisnotConfirmed {
            get {
                return ResourceManager.GetString("Profile:EmailisnotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таҷриба.
        /// </summary>
        internal static string Profile_Experience {
            get {
                return ResourceManager.GetString("Profile:Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маълумоти тажрибаи корӣ бомувафақият инсон карда шуданд.
        /// </summary>
        internal static string Profile_Experiencedetailsadded {
            get {
                return ResourceManager.GetString("Profile:Experiencedetailsadded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таҷриба.
        /// </summary>
        internal static string Profile_Experiences {
            get {
                return ResourceManager.GetString("Profile:Experiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ном.
        /// </summary>
        internal static string Profile_FirstName {
            get {
                return ResourceManager.GetString("Profile:FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Агар шумо хоҳед, ки худро номинатсия кунед, ба мо CV-и худро фиристед..
        /// </summary>
        internal static string Profile_Ifyouwouldliketonominateyourself_sendusyourСV_ {
            get {
                return ResourceManager.GetString("Profile:Ifyouwouldliketonominateyourself,sendusyourСV.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Агар шумо хоҳед, ки худро номинатсия кунед, вуруд шавед ва ба мо CV-и худро фиристед..
        /// </summary>
        internal static string Profile_Ifyouwouldliketonominateyourself_signinandsendusyourСV_ {
            get {
                return ResourceManager.GetString("Profile:Ifyouwouldliketonominateyourself,signinandsendusyourСV.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ин кори ҷорӣ аст.
        /// </summary>
        internal static string Profile_IsCurrentJob {
            get {
                return ResourceManager.GetString("Profile:IsCurrentJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сарвазир.
        /// </summary>
        internal static string Profile_JobTitle {
            get {
                return ResourceManager.GetString("Profile:JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Насаб.
        /// </summary>
        internal static string Profile_LastName {
            get {
                return ResourceManager.GetString("Profile:LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профили ман.
        /// </summary>
        internal static string Profile_MyProfile {
            get {
                return ResourceManager.GetString("Profile:MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таълими нав.
        /// </summary>
        internal static string Profile_NewEducation {
            get {
                return ResourceManager.GetString("Profile:NewEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таҷрибаи нав.
        /// </summary>
        internal static string Profile_NewExperience {
            get {
                return ResourceManager.GetString("Profile:NewExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Калидвожаи куҳна.
        /// </summary>
        internal static string Profile_OldPassword {
            get {
                return ResourceManager.GetString("Profile:OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маълумоти шахсӣ.
        /// </summary>
        internal static string Profile_PersonalInformation {
            get {
                return ResourceManager.GetString("Profile:PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номери телефон дастгирӣ нашудааст.
        /// </summary>
        internal static string Profile_PhoneNumberisnotavailable {
            get {
                return ResourceManager.GetString("Profile:PhoneNumberisnotavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рақами телефон тасдиқ нашудааст!.
        /// </summary>
        internal static string Profile_PhoneNumberisnotConfirmed {
            get {
                return ResourceManager.GetString("Profile:PhoneNumberisnotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лутфан, почтаи худро тасдиқ намоед, мо линкро фиристодаем.
        /// </summary>
        internal static string Profile_Pleasecheckyouremail {
            get {
                return ResourceManager.GetString("Profile:Pleasecheckyouremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ҳозир.
        /// </summary>
        internal static string Profile_Present {
            get {
                return ResourceManager.GetString("Profile:Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профил бомувафақият инсон карда шуд..
        /// </summary>
        internal static string Profile_Profileupdatedsuccessfully {
            get {
                return ResourceManager.GetString("Profile:Profileupdatedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парол бомувафақият инсон карда шуд.
        /// </summary>
        internal static string Profile_Resetpasswordsuccessfully {
            get {
                return ResourceManager.GetString("Profile:Resetpasswordsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сабт кардан.
        /// </summary>
        internal static string Profile_Save {
            get {
                return ResourceManager.GetString("Profile:Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тағйиротро захира кунед.
        /// </summary>
        internal static string Profile_Savechanges {
            get {
                return ResourceManager.GetString("Profile:Savechanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забонро интихоб кунед.
        /// </summary>
        internal static string Profile_SelectLanguage {
            get {
                return ResourceManager.GetString("Profile:SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейли тасдиқро илова кунед.
        /// </summary>
        internal static string Profile_Sendverificationemail {
            get {
                return ResourceManager.GetString("Profile:Sendverificationemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is not responding.
        /// </summary>
        internal static string Profile_Serverisnotresponding {
            get {
                return ResourceManager.GetString("Profile:Serverisnotresponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сервер ҷавоб гирифта намешавад, баъдан дубора санҷед.
        /// </summary>
        internal static string Profile_Servernotrespondingtry {
            get {
                return ResourceManager.GetString("Profile:Servernotrespondingtry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маҳоратҳо.
        /// </summary>
        internal static string Profile_Skills {
            get {
                return ResourceManager.GetString("Profile:Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ихтисос.
        /// </summary>
        internal static string Profile_Specialty {
            get {
                return ResourceManager.GetString("Profile:Specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Санаи оғоз.
        /// </summary>
        internal static string Profile_StartDate {
            get {
                return ResourceManager.GetString("Profile:StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ба темаи торик гузаред.
        /// </summary>
        internal static string Profile_SwitchtoDarkTheme {
            get {
                return ResourceManager.GetString("Profile:SwitchtoDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ба темаи рӯшан гузаред.
        /// </summary>
        internal static string Profile_SwitchtoLightTheme {
            get {
                return ResourceManager.GetString("Profile:SwitchtoLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ба систем гузаред.
        /// </summary>
        internal static string Profile_Switchtosystem {
            get {
                return ResourceManager.GetString("Profile:Switchtosystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ҳолати CV барои номзадии шумо.
        /// </summary>
        internal static string Profile_ThestatusofyourCVforyourcandidacyis {
            get {
                return ResourceManager.GetString("Profile:ThestatusofyourCVforyourcandidacyis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ин рамзи телефон дуруст нест!.
        /// </summary>
        internal static string Profile_Thisphonenumberisnotcorrect {
            get {
                return ResourceManager.GetString("Profile:Thisphonenumberisnotcorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Барои иваз кардани калидвожаи худ, гузарвожаи кӯҳнаи худро ворид кунед ва пас калидвожаи нави қавӣ эҷод кунед..
        /// </summary>
        internal static string Profile_Tochangeyourpassword_enteryouroldpassword_andthencreateanew_strongpassword_ {
            get {
                return ResourceManager.GetString("Profile:Tochangeyourpassword,enteryouroldpassword,andthencreateanew,strongpasswor" +
                        "d.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Боз кӯшиш кунед.
        /// </summary>
        internal static string Profile_TryAgain {
            get {
                return ResourceManager.GetString("Profile:TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Донишгоҳ.
        /// </summary>
        internal static string Profile_University {
            get {
                return ResourceManager.GetString("Profile:University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to То ҳозир.
        /// </summary>
        internal static string Profile_UntilNow {
            get {
                return ResourceManager.GetString("Profile:UntilNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Навсозӣ.
        /// </summary>
        internal static string Profile_Update {
            get {
                return ResourceManager.GetString("Profile:Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таълими бомувафақият инсон карда шуд.
        /// </summary>
        internal static string Profile_UpdateEducationsuccessfully {
            get {
                return ResourceManager.GetString("Profile:UpdateEducationsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV-ро боргузорӣ кунед.
        /// </summary>
        internal static string Profile_UploadCV {
            get {
                return ResourceManager.GetString("Profile:UploadCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV-и навро боргузорӣ кунед.
        /// </summary>
        internal static string Profile_UploadNewCV {
            get {
                return ResourceManager.GetString("Profile:UploadNewCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номи корбар дастгирӣ нашудааст.
        /// </summary>
        internal static string Profile_UserNameisnotavailable {
            get {
                return ResourceManager.GetString("Profile:UserNameisnotavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ивази калидвожа.
        /// </summary>
        internal static string ResetPassword_Changepassword {
            get {
                return ResourceManager.GetString("ResetPassword:Changepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парол бомувафақият инсон карда шуд.
        /// </summary>
        internal static string ResetPassword_Changepasswordsuccessfully {
            get {
                return ResourceManager.GetString("ResetPassword:Changepasswordsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Калидвожаи Нав.
        /// </summary>
        internal static string ResetPassword_NewPassword {
            get {
                return ResourceManager.GetString("ResetPassword:NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рақами мобилӣ.
        /// </summary>
        internal static string ResetPassword_PhoneNumber {
            get {
                return ResourceManager.GetString("ResetPassword:PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рамзи дубора фиристед.
        /// </summary>
        internal static string ResetPassword_Resendcode {
            get {
                return ResourceManager.GetString("ResetPassword:Resendcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рамзи тасдиқро фиристед.
        /// </summary>
        internal static string ResetPassword_Sendconfirmationcode {
            get {
                return ResourceManager.GetString("ResetPassword:Sendconfirmationcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нест карданро тасдиқ кунед.
        /// </summary>
        internal static string Roles_ConfirmDeletion {
            get {
                return ResourceManager.GetString("Roles:ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохтан.
        /// </summary>
        internal static string Roles_Create {
            get {
                return ResourceManager.GetString("Roles:Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохтани роли нав.
        /// </summary>
        internal static string Roles_CreateNewRole {
            get {
                return ResourceManager.GetString("Roles:CreateNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Несткуни.
        /// </summary>
        internal static string Roles_Delete {
            get {
                return ResourceManager.GetString("Roles:Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иваз.
        /// </summary>
        internal static string Roles_Edit {
            get {
                return ResourceManager.GetString("Roles:Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рол.
        /// </summary>
        internal static string Roles_Role {
            get {
                return ResourceManager.GetString("Roles:Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Муваффакият.
        /// </summary>
        internal static string Roles_Success {
            get {
                return ResourceManager.GetString("Roles:Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Навсози.
        /// </summary>
        internal static string Roles_Update {
            get {
                return ResourceManager.GetString("Roles:Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ивазкунии рол.
        /// </summary>
        internal static string Roles_UpdateRole {
            get {
                return ResourceManager.GetString("Roles:UpdateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ҳисоботи шумо вуҷуд надорад? Ба.
        /// </summary>
        internal static string SignIn_LabelDontAccount {
            get {
                return ResourceManager.GetString("SignIn:LabelDontAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Калимаи убуратонро фаромуш кардед?.
        /// </summary>
        internal static string SignIn_LabelForgot {
            get {
                return ResourceManager.GetString("SignIn:LabelForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Бозгузории калимаи убур.
        /// </summary>
        internal static string SignIn_LinkReset {
            get {
                return ResourceManager.GetString("SignIn:LinkReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бақайдгирӣ.
        /// </summary>
        internal static string SignIn_LinkSignUp {
            get {
                return ResourceManager.GetString("SignIn:LinkSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Калимаи убур.
        /// </summary>
        internal static string SignIn_Password {
            get {
                return ResourceManager.GetString("SignIn:Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ворид шудан.
        /// </summary>
        internal static string SignIn_SignIn {
            get {
                return ResourceManager.GetString("SignIn:SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номи корбар.
        /// </summary>
        internal static string SignIn_UserName {
            get {
                return ResourceManager.GetString("SignIn:UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номи корбар ё парол нодуруст.
        /// </summary>
        internal static string SignIn_Wrong_Password {
            get {
                return ResourceManager.GetString("SignIn:Wrong Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тасдиқ кардан.
        /// </summary>
        internal static string SignUp_Apply {
            get {
                return ResourceManager.GetString("SignUp:Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ба пеш.
        /// </summary>
        internal static string SignUp_ButtonNext {
            get {
                return ResourceManager.GetString("SignUp:ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код.
        /// </summary>
        internal static string SignUp_Code {
            get {
                return ResourceManager.GetString("SignUp:Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Калидвожаро Тасдиқ Кунед.
        /// </summary>
        internal static string SignUp_ConfirmPassword {
            get {
                return ResourceManager.GetString("SignUp:ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тасдиқи калимаи убур.
        /// </summary>
        internal static string SignUp_ConfirmPassword_HelperText {
            get {
                return ResourceManager.GetString("SignUp:ConfirmPassword_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почтаи электронӣ.
        /// </summary>
        internal static string SignUp_Email {
            get {
                return ResourceManager.GetString("SignUp:Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идома бо.
        /// </summary>
        internal static string SignUp_ExternalLoginCard {
            get {
                return ResourceManager.GetString("SignUp:ExternalLoginCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ном.
        /// </summary>
        internal static string SignUp_FirstName {
            get {
                return ResourceManager.GetString("SignUp:FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номи худро ворид кунед.
        /// </summary>
        internal static string SignUp_FirstName_HelperText {
            get {
                return ResourceManager.GetString("SignUp:FirstName_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ҳисоботи шумо вуҷуд дорад? .
        /// </summary>
        internal static string SignUp_LabelHaveAccount {
            get {
                return ResourceManager.GetString("SignUp:LabelHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бақайдгирӣ.
        /// </summary>
        internal static string SignUp_LabelSignUp {
            get {
                return ResourceManager.GetString("SignUp:LabelSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Насаб.
        /// </summary>
        internal static string SignUp_LastName {
            get {
                return ResourceManager.GetString("SignUp:LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Насаби худро ворид кунед.
        /// </summary>
        internal static string SignUp_LastName_HelperText {
            get {
                return ResourceManager.GetString("SignUp:LastName_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Ворид шудан.
        /// </summary>
        internal static string SignUp_LinkSignIn {
            get {
                return ResourceManager.GetString("SignUp:LinkSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мо ба ин рақам коди тасдиқро фиристодем: $phone$. Лутфан, шиносоии худро тасдиқ кунед.
        /// </summary>
        internal static string signUp_messageText {
            get {
                return ResourceManager.GetString("signUp:messageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Калимаи убур.
        /// </summary>
        internal static string SignUp_Password {
            get {
                return ResourceManager.GetString("SignUp:Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Калимаи убур.
        /// </summary>
        internal static string SignUp_Password_HelperText {
            get {
                return ResourceManager.GetString("SignUp:Password_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        internal static string SignUp_Phone {
            get {
                return ResourceManager.GetString("SignUp:Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рақами телефони худро ворид кунед.
        /// </summary>
        internal static string SignUp_Phone_HelperText {
            get {
                return ResourceManager.GetString("SignUp:Phone_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кодро боз фиристонидан.
        /// </summary>
        internal static string SignUp_ResendCode {
            get {
                return ResourceManager.GetString("SignUp:ResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сония барои боз фиристодани код боқӣ мондааст..
        /// </summary>
        internal static string SignUp_Secconds {
            get {
                return ResourceManager.GetString("SignUp:Secconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номи корбар.
        /// </summary>
        internal static string SignUp_UserName {
            get {
                return ResourceManager.GetString("SignUp:UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ҷавобҳо.
        /// </summary>
        internal static string UserButton_Applications {
            get {
                return ResourceManager.GetString("UserButton:Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баромад.
        /// </summary>
        internal static string UserButton_Logout {
            get {
                return ResourceManager.GetString("UserButton:Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хуҷраи шахсӣ.
        /// </summary>
        internal static string UserButton_Profile {
            get {
                return ResourceManager.GetString("UserButton:Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Воридшавӣ.
        /// </summary>
        internal static string UserButton_Sign_In {
            get {
                return ResourceManager.GetString("UserButton:Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бақайдгирӣ.
        /// </summary>
        internal static string UserButton_Sign_Up {
            get {
                return ResourceManager.GetString("UserButton:Sign Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номи пурра.
        /// </summary>
        internal static string UserManager_FullName {
            get {
                return ResourceManager.GetString("UserManager:FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бор карда мешавад....
        /// </summary>
        internal static string UserManager_Loading {
            get {
                return ResourceManager.GetString("UserManager:Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ягон сабти мувофиқ ёфт нашуд.
        /// </summary>
        internal static string UserManager_Nomatchingrecords {
            get {
                return ResourceManager.GetString("UserManager:Nomatchingrecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нақшҳо.
        /// </summary>
        internal static string UserManager_Roles {
            get {
                return ResourceManager.GetString("UserManager:Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ҷустуҷӯ аз рӯи номи корбар ё номи пурра.
        /// </summary>
        internal static string UserManager_Searchname {
            get {
                return ResourceManager.GetString("UserManager:Searchname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Истифодабарандагон.
        /// </summary>
        internal static string UserManager_Users {
            get {
                return ResourceManager.GetString("UserManager:Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ҷинс.
        /// </summary>
        internal static string UserRoles_Gender {
            get {
                return ResourceManager.GetString("UserRoles:Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таърих.
        /// </summary>
        internal static string UserRoles_History {
            get {
                return ResourceManager.GetString("UserRoles:History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маълумоти шахсӣ.
        /// </summary>
        internal static string UserRoles_PersonalData {
            get {
                return ResourceManager.GetString("UserRoles:PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тасдиқ нашудааст.
        /// </summary>
        internal static string UserRoles_UnConfirmed {
            get {
                return ResourceManager.GetString("UserRoles:UnConfirmed", resourceCulture);
            }
        }
    }
}
